### ISSUE TITLE
Move toread.md into google-sheets

### ISSUE THREAD

**Issue by escorciav** [IVUL-KAUST/GroupReading#6]
Shall we move the content of [the file](https://github.com/IVUL-KAUST/GroupReading/blob/master/toread.md) into google-sheets?
I don't think that markdown is the best format for this because:
-  we are constantly editing the file
- we can't vote or rank papers based on popularity :wink: 

c.c. @adelbibi @SilvioGiancola @Frostinassiky  @lightaime

**Comment by frostinassiky** [comment]
If someone edits the file, can he merge the change to the master branch direct? If yes, I think the current method is fine.

**Comment by lightaime** [comment]
Maybe we can share this file to slack group meeting channel. If the person
selecting papers is interested in those papers, he can select from those.

Best,
Guohao

**Comment by frostinassiky** [comment]
@lightaime Good idea. What if we use [Mendeley](https://www.mendeley.com/) instead? It is a paper-manage system. We can set up an IVUL group, and share all the papers. 
With Mendeley, 

1.  We can have the same version of the paper
2. Notes are shared
3. Anyone can upload any paper
4. Adding/Editing a paper is fast

**Comment by SilvioGiancola** [comment]
Mendeley could be a good idea, anyone want to take charge of that? 
It is worth giving it a chance now since after Feb 19th, we don't have anyone to pick papers. It could become a democratic thing with a larger list of paper.

**Comment by escorciav** [comment]
I moved the list to [this](https://docs.google.com/spreadsheets/d/1sxOOSXRQjaHoi2MPfeKsdgEUnS0qD3di11c4XcMdsTc/edit#gid=0) google sheets doc.

I can send a PR if you are okay with that and close the issue.

I prefer google-sheets because we click it and have access to it nearly everywhere without login or additional software/plugins. At the end of the day, we just need an inbox where to drop papers and sort easily based on preference 😉.

**Comment by escorciav** [comment]
@Frostinassiky @SilvioGiancola pls lemme know if u buy the g-sheets idea.
If that's the case, I will add it to the repo and close the issue.

**Comment by SilvioGiancola** [comment]
I like the g-sheet idea better, easier to update without the cumbersome pulling/commiting/pushing. 
In the end, this list is only a list a paper to read, as soon as it someone presents the paper, the presentation will be added to the github repo.
